# By default, this will use docker image circleci/node:latest
# And cache npm dependencies by branch + checksum "package.json"
#
# Dockerfiles:
# https://github.com/CircleCI-Public/circleci-dockerfiles/master/node/images/13.8.0-stretch/Dockerfile
# Reference: https://circleci.com/docs/2.0/circleci-images/
#
# To see a dump of process setup under-the-hood locally, run
# > circleci config process config.yml
#
# Run locally (requires docker + circleci) with makefile:
# > CI_JOB=build make run-ci
#
# There is also support for testing w/ GPUs, if we need it for rendering:
# https://circleci.com/docs/2.0/executor-types/#using-gpus

# Plugins that provide some helpful commands: https://circleci.com/orbs/
# https://circleci.com/orbs/registry/orb/circleci/slack
version: 2.1

orbs:
  node: circleci/node@1.1.6
  slack: circleci/slack@3.4.2

# Yaml references
references:
  workspace_root: &workspace_root
    ~/workspace
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

# Pipelines => collections of jobs defined below
workflows:
  version: 2

  build-and-test:
    jobs:
      - js_setup
      - test_source:
          requires:
            - js_setup
      - coverage:
          requires:
            - js_setup

  # Can trigger a rebuild of gh-pages when master is updated
  build-deploy:
    jobs:
      - js_setup
      - deploy:
          requires:
            - js_setup
          filters:
            branches:
              only: master


jobs:
  js_setup:
    executor: # this executor is from the node orb
      name: node/default
    steps:
      - *attach_workspace
      - checkout                     # get the code from GitHub
      - node/with-cache:             # orb command => restoring/saving a cache
          cache-key: "package.json"  # change to yarn.lock?
          cache-version: v1          # update to invalidate cache
          steps:
            - run: npm install --loglevel=error
            - run: npm install codecov --loglevel=error

  test_source:                                    # run basic tests
    executor:
      name: node/default
    steps:
      - *attach_workspace
      - run: npm test

  coverage:
    executor:
      name: node/default
    steps:
      - *attach_workspace
      - run: npm install codecov
      - run: npm run codecov
      - run: bash <(curl -s https://codecov.io/bash)

  deploy:                                         # deploy to gh-pages
    executor:
      name: node/default
    steps:
      - *attach_workspace
      - run: npm run deploy
